apply plugin: 'com.android.application'

android {
    namespace "com.cyorg24.dwelling_nia"

    compileSdkVersion 33

    defaultConfig {
//        applicationId "com.cyorg24.dwelling_nia"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 3
        versionName "3.0.0-J"

//        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    productFlavors {
        flavorDimensions += "rate"

        premium013 {
            applicationId "com.cyorg24.dwelling013"
            resValue "string", "app_name", "Dwelling 13"
            buildConfigField  "double", "BASIC_PREMIUM", "0.13"
            versionNameSuffix "-013"
        }
        premium015 {
            applicationId "com.cyorg24.dwelling015"
            resValue "string", "app_name", "Dwelling 15"
            buildConfigField  "double", "BASIC_PREMIUM", "0.15"
            versionNameSuffix "-015"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'com.google.android.material:material:1.0.0'
    testImplementation 'junit:junit:4.12'
}
